name: bteConoSur
version: 2.0
main: pizzaaxx.bteconosur.BTEConoSur

depend:
  - WorldEdit
  - WorldGuard

commands:
  city:
    description: Manage cities.
    permission: bteconosur.city.admin
  increment:
    description: Cambia el incremento al usar los atajos de WorldEdit.
    aliases:
      - incremento
      - /increment
      - /incremento
  link:
    description: Conecta tu cuenta de Minecraft a tu cuenta de Discord.
  unlink:
    description: Desconecta tu cuenta de Minecraft de tu cuenta de Discord.
  tpdir:
    description: Teletransp´órtate a un lugar por su nombre.
  deletePlayerData:
    description: Elimina el archivo de playerdata de un jugador con su UUID.
    permission: op
  height:
    description: Obtén tu altitud actual. Útil en Bedrock.
    aliases:
      - h
  googleMaps:
    description: Obtén un link a GoogleMaps de tu posición actual.
    aliases:
      - gmaps
      - gm
  banners:
    description: Obtén estandartes de letras basados en un texto.
    aliases:
      - banner
  get:
    description: Obtén acceso a bloques especiales.
  /polywalls:
    description: Crea paredes de selecciones poligonales.
  pwarp:
    description: Maneja tus warps personales.
  asset:
    description: Maneja los assets.
  assetgroup:
    description: Maneja tus grupos de assets.
  /assetfill:
    description: Llena una zona con assets de un grupo.
  /divide:
    description: Divide a line into multiple divisions.
  /terraform:
    description: Genera terreno basado en diferentes alturas dentro de un polígono.
    aliases:
      - terraform
      - tf
      - /tf
  preset:
    description: Pedazos de texto que se reemplazan en comandos.
    aliases:
      - presets
  /selredo:
    description: Rehace una selección.
    aliases:
      - /sr
      - /sredo
  /selundo:
    description: Deshace una selección.
    aliases:
      - /su
      - /sundo
  nightvision:
    description: Da o quita el efecto de visión nocturna.
    aliases:
      - nv
  drawPolygon:
    description: Testing.
  project:
    description: Proyectos.
    aliases:
      - p
  chat:
    description: Chats.
    aliases:
      - c