name: bteConoSur
version: 2.0
main: pizzaaxx.bteconosur.BTEConoSur

depend:
  - WorldEdit
  - WorldGuard

commands:
  city:
    description: Manage cities.
    permission: bteconosur.city.admin
  increment:
    description: Cambia el incremento al usar los atajos de WorldEdit.
    aliases:
      - incremento
      - /increment
      - /incremento
  link:
    description: Conecta tu cuenta de Minecraft a tu cuenta de Discord.
  unlink:
    description: Desconecta tu cuenta de Minecraft de tu cuenta de Discord.
  tpdir:
    description: Teletransp´órtate a un lugar por su nombre.
  deletePlayerData:
    description: Elimina el archivo de playerdata de un jugador con su UUID.
    permission: op
  height:
    description: Obtén tu altitud actual. Útil en Bedrock.
    aliases:
      - h
  googleMaps:
    description: Obtén un link a GoogleMaps de tu posición actual.
    aliases:
      - gmaps
      - gm
  banners:
    description: Obtén estandartes de letras basados en un texto.
    aliases:
      - banner
  get:
    description: Obtén acceso a bloques especiales.
  /polywalls:
    description: Crea paredes de selecciones poligonales.
  pwarp:
    description: Maneja tus warps personales.
  asset:
    description: Maneja los assets.
  assetgroup:
    description: Maneja tus grupos de assets.
  /divide:
    description: Divide a line into multiple divisions.