name: bteConoSur
version: 2.0
main: pizzaaxx.bteconosur.BTEConoSur

depend:
  - WorldEdit
  - WorldGuard

commands:
  city:
    description: Manage cities.
    permission: bteconosur.city.admin
  increment:
    description: Cambia el incremento al usar los atajos de WorldEdit.
    aliases:
      - incremento
      - /increment
      - /incremento