name: bteConoSur
version: 2.0
main: pizzaaxx.bteconosur.BTEConoSur

depend:
  - WorldEdit
  - WorldGuard

commands:
  city:
    description: Manage cities.
    permission: bteconosur.city.admin
  increment:
    description: Cambia el incremento al usar los atajos de WorldEdit.
    aliases:
      - incremento
      - /increment
      - /incremento
  link:
    description: Conecta tu cuenta de Minecraft a tu cuenta de Discord.
  unlink:
    description: Desconecta tu cuenta de Minecraft de tu cuenta de Discord.
  tpdir:
    description: Teletransp´órtate a un lugar por su nombre.
  deletePlayerData:
    description: Delete a player's data file based on its UUID.
    permission: op