name: bteConoSur
version: 3.0
author: PIZZAAXX
main: pizzaaxx.bteconosur.BTEConoSurPlugin

api-version: '1.20'

loadbefore:
  - TAB
  - bteChileBot

depend:
  - WorldEdit
  - Terraplusminus

commands:
  tpll:
    description: Teletranspórtate a un par de coordenadas geográficas.
  tpdir:
    description: Teletranspórtate a una dirección del mundo.
  divide:
    description: Crea una linea que está dividida en partes iguales.
  link:
    description: Enlaza tu cuenta de Discord con tu cuenta de Minecraft.
  unlink:
    description: Desenlaza tu cuenta de Discord con tu cuenta de Minecraft.
  sc:
    description: Maneja el scoreboard.
  project:
    description: Maneja los proyectos.
  nightvision:
    description: Activa o desactiva la visión nocturna.
    aliases:
      - nv
  reloadplayer:
    description: Recarga los datos de un jugador.
  height:
    description: Muestra la altura de un jugador.
  increment:
    description: Cambia el incremento de WorldEdit de un jugador.
  enderchest:
    description: Abre el enderchest de un jugador.
    aliases:
      - ec
  hat:
    description: Pon un bloque en tu cabeza.
  back:
    description: Teletranspórtate a tu última posición.
  clearinventory:
    description: Limpia tu inventario.
    aliases:
      - ci
  jump:
    description: Atraviesa una pared que estés mirando.
  ptime:
    description: Cambia el tiempo de un jugador.
  tpoffline:
    description: Teletransportate a la ultima ubicación de un jugador offline.
  /polywalls:
    description: Crea paredes de un polígono.
  banner:
    aliases:
      - banners
    description: Obtén los banners de un texto.
  vanish:
    description: Activa o desactiva el modo invisible.
  tptoggle:
    description: Activa o desactiva el teletransporte hacia ti.
  tp:
    description: Teletransportate.
  editsign:
    description: Edita un cartel.
  pweather:
    description: Cambia el clima de un jugador.
  skull:
    description: Obtén la cabeza de un jugador.
  kick:
    description: Kickea a un jugador.
  ban:
    description: Banea a un jugador.
  tempban:
    description: Banea temporalmente a un jugador.
  unban:
    description: Desbanea a un jugador.
  banip:
    description: Banea la IP de un jugador.
  tempbanip:
    description: Banea temporalmente la IP de un jugador.
  unbanip:
    description: Desbanea la IP de un jugador.