name: bteConoSur
version: 3.0
author: PIZZAAXX
main: pizzaaxx.bteconosur.BTEConoSurPlugin

api-version: '1.20'

loadbefore:
  - TAB
  - bteChileBot

depend:
  - WorldEdit
  - Terraplusminus

commands:
  tpll:
    description: Teletranspórtate a un par de coordenadas geográficas.
  tpdir:
    description: Teletranspórtate a una dirección del mundo.
  divide:
    description: Crea una linea que está dividida en partes iguales.
  link:
    description: Enlaza tu cuenta de Discord con tu cuenta de Minecraft.
  unlink:
    description: Desenlaza tu cuenta de Discord con tu cuenta de Minecraft.
  sc:
    description: Maneja el scoreboard.
  project:
    description: Maneja los proyectos.
  nightvision:
    description: Activa o desactiva la visión nocturna.
    aliases:
      - nv
  reloadplayer:
    description: Recarga los datos de un jugador.
  height:
    description: Muestra la altura de un jugador.
  increment:
    description: Cambia el incremento de WorldEdit de un jugador.
  enderchest:
    description: Abre el enderchest de un jugador.
    aliases:
      - ec
  hat:
    description: Pon un bloque en tu cabeza.
  back:
    description: Teletranspórtate a tu última posición.
  clearinventory:
    description: Limpia tu inventario.
    aliases:
      - ci
  jump:
    description: Atraviesa una pared que estés mirando.
  ptime:
    description: Cambia el tiempo de un jugador.