name: bteConoSur
version: 3.0
author: PIZZAAXX
main: pizzaaxx.bteconosur.BTEConoSurPlugin

api-version: '1.20'

loadbefore:
  - TAB
  - bteChileBot

depend:
  - WorldEdit
  - WorldGuard
  - Terraplusminus

commands:
  tpll:
    description: Teletranspórtate a un par de coordenadas geográficas.
    permission: btecs.tpll
  divide:
    description: Crea una linea que está dividida en partes iguales.
    permission: btecs.divide
  link:
    description: Enlaza tu cuenta de Discord con tu cuenta de Minecraft.
    permission: btecs.link
  unlink:
    description: Desenlaza tu cuenta de Discord con tu cuenta de Minecraft.
    permission: btecs.link

permissions:
  btecs.tpll:
    default: not op
  btecs.divide:
    default: not op
  btecs.link:
    default: not op
